<!--
 * 
 * @author Anuj
 * @date   31 May, 2014
 * @version 1.0
-->
<!--Content Wrapper -->
<section id="wrapper">
    <div id="inner-wrapper">
	<?php// echo error_reporting(1);exit; "rrtrt";exit;?>
        <h1><?php echo $this->translate('Change Password'); ?></h1>
        <div class="error-messages">
        <?php
        if (!empty($this->messages)) {
            $error = '<div class="alert alert-danger"><a class="close" data-dismiss="alert">Ã</a><strong>Error! </strong>'
                    . $this->messages . '</div</div </div></div></div>';
            echo $error;
        }
        ?>
        </div>    
        <div class="edit-event-form white-bg padding20">
            <form class="form-horizontal" role="form" name="changepassword" action="" method="POST"> 

                <?php //echo "<pre>";print_R($this->form->getElement("dealer_name"));//echo "<pre>";print_r($this->EventData); ?>

                <div class="row">
                    <div class="col-md-4 col-md-offset-1">
                        <div class="form-group">
                            <label for="old_password" class="control-label"><?php echo $this->form->old_password->renderLabel() ?></label>
                                <?php echo $this->form->old_password->renderViewHelper(); ?>
                        </div>
                    </div>
               </div>
		<div class = "row">     
                    <div class="col-md-4 col-md-offset-1">
                        <div class="form-group">
                            <label for="new_password" class="control-label"><?php echo $this->form->new_password->renderLabel() ?></label>
                                <?php echo $this->form->new_password->renderViewHelper(); ?>
                        </div>
                    </div>
                    </div>
<div class ="row">
                    <div class="col-md-4 col-md-offset-1">
                        <div class="form-group">
                            <label for="confirm_password" class="control-label"><?php echo $this->form->confirm_password->renderLabel() ?></label>
                                <?php echo $this->form->confirm_password->renderViewHelper(); ?>
                        </div>
                    </div>
</div>

                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="text-center save-btn-row">
                                <?php echo $this->form->submitbtn->renderViewHelper(); ?>
                                
                            </div>
                        </div>
                    </div>
                </div>

                
                
            </form>
        </div>
    </div>
</section>
<script>
    $(document).ready(function () 
    {
        $('#submit').on('click',function()
        {
            var errors = new Array();
        
            jQuery('.error-messages').html('');
            
            if ($('#old_password').val() == '') 
            {
                errors.push('Please enter old password');
            }
            
            if ($('#new_password').val() == '') 
            {
                errors.push('Please enter new password');
            }
            
            if ($('#confirm_password').val() == '') 
            {
                errors.push('Please enter confirm password');
            }
        
           
		var newPasswordVal = $('#new_password').val();
            var confirmPasswordVal = $('#confirm_password').val();
            if(newPasswordVal!='' && confirmPasswordVal!=''){
                if(newPasswordVal!=confirmPasswordVal){
                    errors.push('New password and confirm password does not match');
                }
            }
            
            if(errors.length != 0)
            {
                var errorHtml = '<div class=""><div class="alert alert-danger"><a class="close" data-dismiss="alert">Ã</a><strong>Error! </strong><br/>';
                    for (i = 0; i < errors.length; i++) 
                    {
                       errorHtml += errors[i] + "<br>";
                    }

                errorHtml +=  '</div</div </div></div></div>';

                jQuery('.error-messages').html(errorHtml);
                return false;
            }         
        
        });
	}); 
</script>

