<div class="survey_start_content">
	<center>
	<div>
	<?php
            echo $this->survey_notexist_orclosed; 
        /*if($this->closedevent == "yes") {
			echo $this->translate('survey_index_notexist-orclosed');
	}else {
	
		if($this->editsubmitsurvey == false &&  $this->session->act == "edit") {?>
			<?php echo $this->translate('survey_index_not-authorise-to-edit-survey'); ?>
		<?php } else  {?>
			<?php echo $this->translate('survey_index_notexist-orclosed'); ?>
		<?php }
	}*/ ?>
	</div>
	</center>
</div>