<h1><div class="logo col-lg-6 col-md-6 col-md-offset-3 col-sm-6"><img src="<?php echo $this->baseUrl()."/images/logo.jpg";?>" alt="Triumph"></div></h1>
<?php
		if(count($this->flashMessages)){
			foreach($this->flashMessages as $error){
				echo"<div class='alert alert-danger'>".$error."</div>";
			}
			
		}
	?>	

    <div class="clearfix"></div>
        <form class="form" id="adminlogin" name="adminlogin" action="<?php echo $this->url( array( 'module' => 'default', 'controller' => 'index', 'action' => 'index' ), 'default', true ); ?>" method="post">
        	<div class="form-group">
            	<label for="name">Username</label>
                <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
				<?php echo $this->form->username;?>
                </div>
            </div>
            <div class="form-group">
            	<label for="name">Password</label>
                <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
				<?php echo $this->form->password;?>
                </div>
            </div>
            <div class="form-group">
		<?php echo $this->form->Login;?>
            </div>
<!--            <div class="form-group forgot-pwd">
            	<ul class="list-inline">
                <li><label for=""><input type="checkbox"> Remember Me</label></li>
                <li><p class="form-control-static"><a href="forgot-password.html">Forgot Password ?</a></p></li>
                </ul>
            	
            </div>-->
        </form>
   			