<!--
 * 
 * @author Anuj
 * @date   31 May, 2014
 * @version 1.0
-->
<!--Content Wrapper -->


<section id="wrapper">
    <div id="inner-wrapper">

        <h2><?php echo $this->translate('View Survey'); ?></h2>

        <?php
        if (!empty($this->messages)) {
            $error = '<div class=""><div class="alert alert-danger"><a class="close" data-dismiss="alert">×</a><strong>Error! </strong>'
                    . $this->messages . '</div</div </div></div></div>';
            echo $error;
        }
        ?>
        <div class="edit-event-form white-bg padding20">
            <form class="form-horizontal" role="form" name="editevent" action="" method="POST"> 

                <?php //echo "<pre>";print_R($this->form->getElement("dealer_name"));//echo "<pre>";print_r($this->EventData); ?>
                <div class="form-group">
                    <label for="survey_category" class="col-md-3 col-sm-4"><?php echo $this->form->survey_category->renderLabel() ?></label>
                    <div class="col-sm-5">
                        <?php echo $this->form->survey_category->renderViewHelper(); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label for="dealer_name" class="col-md-3 col-sm-4"><?php  echo $this->form->event_type->renderLabel() ?></label>
                    <div class="col-sm-5">
                        <?php echo $this->form->event_type->renderViewHelper(); ?>
                         <?php echo $this->form->survey_id->renderViewHelper(); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email_address" class="col-md-3 col-sm-4"><?php  echo $this->form->survey_name->renderLabel(); ?></label>
<div class="col-sm-5">
                         <?php echo $this->form->survey_name->renderViewHelper(); ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="email_address" class="col-md-3 col-sm-4"><?php echo $this->form->start_date->renderLabel(); ?></label>
                    <div class="col-sm-5">
                         <?php echo $this->form->start_date->renderViewHelper(); ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="email_address" class="col-md-3 col-sm-4"><?php echo $this->form->end_date->renderLabel(); ?></label>
                    <div class="col-sm-5">
                         <?php echo $this->form->end_date->renderViewHelper(); ?>
                    </div>
                </div>
				
                <div class="form-group">
                    <div class="col-sm-5 col-md-offset-3 col-sm-offset-4">
                        
                        <button id="backButton" type="button" onclick="goBack();" class="btn btn-primary"><?php echo $this->translate('Back'); ?></button> 
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<script>
    $(document).ready(function () {
        $("#start_date").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy',            
        });
        
        $("#end_date").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy',            
        });
     });

</script>