<!--
 * 
 * @author Anuj
 * @date   31 May, 2014
 * @version 1.0
-->
<!--Content Wrapper -->


<section id="wrapper">
    <div id="inner-wrapper">

        <h2><?php echo $this->translate('Edit Event'); ?></h2>

        <?php
        if (!empty($this->messages)) {
            $error = '<div class=""><div class="alert alert-danger"><a class="close" data-dismiss="alert">×</a><strong>Error! </strong>'
                    . $this->messages . '</div</div </div></div></div>';
            echo $error;
        }
        ?>
        <div class="edit-event-form white-bg padding20">
            <form class="form-horizontal" role="form" name="editevent" action="" method="POST"> 

                <?php //echo "<pre>";print_R($this->form->getElement("dealer_name"));//echo "<pre>";print_r($this->EventData); ?>

                <div class="form-group">


                    <label for="dealer_name" class="col-md-3 col-sm-4"><?php echo $this->translate('Dealer'); ?></label>

                    <div class="col-sm-5">


                        <?php echo $this->form->getElement("dealer_id"); ?>
                    </div>
                </div>

                <div class="form-group">


                    <label for="email_address" class="col-md-3 col-sm-4"><?php echo $this->translate('Email'); ?></label>

                    <div class="col-sm-5">
                        <?php echo $this->form->getElement("email_address") ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-5 col-md-offset-3 col-sm-offset-4">

                        <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save Changes'); ?></button>
                        <button type="submit" class="btn btn-primary"><?php echo $this->translate('Cancel'); ?></button>

                    </div>
                </div>
            </form>
        </div>
    </div>
</section>